"""Initial schema

Revision ID: 9b05f114baa5
Revises: 
Create Date: 2025-11-10 01:30:33.586628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b05f114baa5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('states',
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('state_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('state_id')
    )
    op.create_index(op.f('ix_states_state_id'), 'states', ['state_id'], unique=False)
    op.create_index(op.f('ix_states_state_name'), 'states', ['state_name'], unique=True)
    op.create_table('districts',
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('district_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['state_id'], ['states.state_id'], ),
    sa.PrimaryKeyConstraint('district_id')
    )
    op.create_index(op.f('ix_districts_district_id'), 'districts', ['district_id'], unique=False)
    op.create_index(op.f('ix_districts_district_name'), 'districts', ['district_name'], unique=False)
    op.create_index(op.f('ix_districts_state_id'), 'districts', ['state_id'], unique=False)
    op.create_table('mandals',
    sa.Column('mandal_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('mandal_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.district_id'], ),
    sa.PrimaryKeyConstraint('mandal_id')
    )
    op.create_index(op.f('ix_mandals_district_id'), 'mandals', ['district_id'], unique=False)
    op.create_index(op.f('ix_mandals_mandal_id'), 'mandals', ['mandal_id'], unique=False)
    op.create_index(op.f('ix_mandals_mandal_name'), 'mandals', ['mandal_name'], unique=False)
    op.create_table('villages',
    sa.Column('village_id', sa.Integer(), nullable=False),
    sa.Column('mandal_id', sa.Integer(), nullable=False),
    sa.Column('village_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['mandal_id'], ['mandals.mandal_id'], ),
    sa.PrimaryKeyConstraint('village_id')
    )
    op.create_index(op.f('ix_villages_mandal_id'), 'villages', ['mandal_id'], unique=False)
    op.create_index(op.f('ix_villages_village_id'), 'villages', ['village_id'], unique=False)
    op.create_index(op.f('ix_villages_village_name'), 'villages', ['village_name'], unique=False)
    op.create_table('registrations',
    sa.Column('registration_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone_e164', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('mandal_id', sa.Integer(), nullable=False),
    sa.Column('village_id', sa.Integer(), nullable=False),
    sa.Column('utm_source', sa.String(length=100), nullable=True),
    sa.Column('utm_medium', sa.String(length=100), nullable=True),
    sa.Column('utm_campaign', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.district_id'], ),
    sa.ForeignKeyConstraint(['mandal_id'], ['mandals.mandal_id'], ),
    sa.ForeignKeyConstraint(['state_id'], ['states.state_id'], ),
    sa.ForeignKeyConstraint(['village_id'], ['villages.village_id'], ),
    sa.PrimaryKeyConstraint('registration_id')
    )
    op.create_index(op.f('ix_registrations_created_at'), 'registrations', ['created_at'], unique=False)
    op.create_index(op.f('ix_registrations_email'), 'registrations', ['email'], unique=False)
    op.create_index(op.f('ix_registrations_name'), 'registrations', ['name'], unique=False)
    op.create_index(op.f('ix_registrations_phone_e164'), 'registrations', ['phone_e164'], unique=True)
    op.create_index(op.f('ix_registrations_registration_id'), 'registrations', ['registration_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registrations_registration_id'), table_name='registrations')
    op.drop_index(op.f('ix_registrations_phone_e164'), table_name='registrations')
    op.drop_index(op.f('ix_registrations_name'), table_name='registrations')
    op.drop_index(op.f('ix_registrations_email'), table_name='registrations')
    op.drop_index(op.f('ix_registrations_created_at'), table_name='registrations')
    op.drop_table('registrations')
    op.drop_index(op.f('ix_villages_village_name'), table_name='villages')
    op.drop_index(op.f('ix_villages_village_id'), table_name='villages')
    op.drop_index(op.f('ix_villages_mandal_id'), table_name='villages')
    op.drop_table('villages')
    op.drop_index(op.f('ix_mandals_mandal_name'), table_name='mandals')
    op.drop_index(op.f('ix_mandals_mandal_id'), table_name='mandals')
    op.drop_index(op.f('ix_mandals_district_id'), table_name='mandals')
    op.drop_table('mandals')
    op.drop_index(op.f('ix_districts_state_id'), table_name='districts')
    op.drop_index(op.f('ix_districts_district_name'), table_name='districts')
    op.drop_index(op.f('ix_districts_district_id'), table_name='districts')
    op.drop_table('districts')
    op.drop_index(op.f('ix_states_state_name'), table_name='states')
    op.drop_index(op.f('ix_states_state_id'), table_name='states')
    op.drop_table('states')
    # ### end Alembic commands ###
