-- =====================================================
-- ANDHRA PRADESH COMPLETE MANDALS DATA
-- Total: 679 mandals across 26 districts
-- Source: Wikipedia - List of mandals of Andhra Pradesh
-- Date: November 2025
-- =====================================================

-- Clear all existing mandals (keeps districts intact)
TRUNCATE TABLE mandals RESTART IDENTITY CASCADE;

-- =====================================================
-- INSERT ALL MANDALS
-- =====================================================

-- Alluri Sitharama Raju District (district_id = 14) - 22 mandals
INSERT INTO mandals (mandal_name, district_id) VALUES ('Y. Ramavaram', 6);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Vararamachandrapuram', 6);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Rampachodavaram', 6);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Rajavommangi', 6);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Peda Bayalu', 6);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Paderu', 6);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Munchingi Puttu', 6);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Maredumilli', 6);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kunavaram', 6);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Koyyuru', 6);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Hukumpeta', 6);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Gudem Kotha Veedhi', 6);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Gangavaram', 6);
INSERT INTO mandals (mandal_name, district_id) VALUES ('G. Madugula', 6);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Etapaka', 6);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Dumbriguda', 6);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Devipatnam', 6);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Chintur', 6);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Chintapalle', 6);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Araku Valley', 6);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Ananthagiri', 6);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Addateegala', 6);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Sarvasiddhi Rayavaram', 5);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Sabbavaram', 5);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Rolugunta', 5);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Ravikamatham', 5);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Rambilli', 5);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Payakaraopeta', 5);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Paravada', 5);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Nathavaram', 5);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Narsipatnam', 5);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Nakkapalle', 5);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Munagapaka', 5);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Makavarapalem', 5);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Madugula', 5);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kotauratla', 5);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kasimkota', 5);
INSERT INTO mandals (mandal_name, district_id) VALUES ('K.Kotapadu', 5);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Golugonda', 5);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Elamanchili', 5);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Devarapalli', 5);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Chodavaram', 5);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Cheedikada', 5);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Butchayyapeta', 5);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Atchutapuram', 5);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Anakapalle', 5);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Yellanur', 23);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Yadiki', 23);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Vidapanakal', 23);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Vajrakarur', 23);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Uravakonda', 23);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Tadipatri', 23);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Singanamala', 23);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Settur', 23);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Rayadurg', 23);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Raptadu', 23);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Putlur', 23);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Peddavadugur', 23);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Peddapappur', 23);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Pamidi', 23);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Narpala', 23);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kundurpi', 23);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kudair', 23);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kanekal', 23);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kambadur', 23);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kalyandurg', 23);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Guntakal', 23);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Gummagatta', 23);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Gooty', 23);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Garladinne', 23);
INSERT INTO mandals (mandal_name, district_id) VALUES ('D.Hirehal', 23);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Bukkaraya Samudram', 23);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Brahmasamudram', 23);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Bommanahal', 23);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Beluguppa', 23);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Atmakur', 23);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Anantapur', 23);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Veeraballi', 21);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Valmikipuram', 21);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Thamballapalle', 21);
INSERT INTO mandals (mandal_name, district_id) VALUES ('T. Sundupalle', 21);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Somala', 21);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Sodam', 21);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Sambepalli', 21);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Rompicherla', 21);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Rayachoti', 21);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Ramasamudram', 21);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Ramapuram', 21);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Rajampet', 21);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Punganur', 21);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Pullampeta', 21);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Pulicherla', 21);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Pileru', 21);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Penagalur', 21);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Peddathippasamudram', 21);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Peddamandyam', 21);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Obulavaripalle', 21);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Nimmanapalle', 21);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Nandalur', 21);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Mulakalacheruvu', 21);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Madanapalle', 21);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Lakkireddypalli', 21);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kurabalakota', 21);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kodur', 21);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kalikiri', 21);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kalakada', 21);
INSERT INTO mandals (mandal_name, district_id) VALUES ('K. V. Palle', 21);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Gurramkonda', 21);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Galiveedu', 21);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Chowdepalle', 21);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Chitvel', 21);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Chinnamandyam', 21);
INSERT INTO mandals (mandal_name, district_id) VALUES ('B. Kothakota', 21);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Yeddanapudi', 16);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Vetapalem', 16);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Vemuru', 16);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Tsundur', 16);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Santhamaguluru', 16);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Repalle', 16);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Pittalavanipalem', 16);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Parchur', 16);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Nizampatnam', 16);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Nagaram', 16);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Martur', 16);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Korisapadu', 16);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kolluru', 16);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Karlapalem', 16);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Karamchedu', 16);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Janakavarampanguluru', 16);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Inkollu', 16);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Chirala', 16);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Chinaganjam', 16);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Cherukupalle', 16);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Bhattiprolu', 16);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Bapatla', 16);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Ballikurava', 16);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Amruthalur', 16);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Addanki', 16);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Yadamarri', 20);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Vijayapuram', 20);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Venkatagirikota', 20);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Vedurukuppam', 20);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Thavanampalle', 20);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Sri Rangaraja Puram', 20);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Santhipuram', 20);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Ramakuppam', 20);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Puthalapattu', 20);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Punganur', 20);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Penumuru', 20);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Peddapanjani', 20);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Palasamudram', 20);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Palamaner', 20);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Nindra', 20);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Nagari', 20);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kuppam', 20);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Karvetinagar', 20);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Irala', 20);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Gudipalle', 20);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Gudipala', 20);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Gangavaram', 20);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Gangadhara Nellore', 20);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Chittoor', 20);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Bangarupalem', 20);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Baireddipalle', 20);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Uppalaguptam', 9);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Sakhinetipalle', 9);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Razole', 9);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Rayavaram', 9);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Ravulapalem', 9);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Ramachandrapuram', 9);
INSERT INTO mandals (mandal_name, district_id) VALUES ('P. Gannavaram', 9);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Mummidivaram', 9);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Mandapeta', 9);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Mamidikuduru', 9);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Malikipuram', 9);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kothapeta', 9);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Katrenikona', 9);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kapileswarapuram', 9);
INSERT INTO mandals (mandal_name, district_id) VALUES ('K. Gangavaram', 9);
INSERT INTO mandals (mandal_name, district_id) VALUES ('I. Polavaram', 9);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Atreyapuram', 9);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Ambajipeta', 9);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Amalapuram', 9);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Allavaram', 9);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Alamuru', 9);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Ainavilli', 9);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Undrajavaram', 8);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Tallapudi', 8);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Seethanagaram', 8);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Rangampeta', 8);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Rajanagaram', 8);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Rajahmundry Urban', 8);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Rajahmundry Rural', 8);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Peravali', 8);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Nidadavole', 8);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Nallajerla', 8);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kovvur', 8);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Korukonda', 8);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kadiam', 8);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Gopalapuram', 8);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Gokavaram', 8);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Devarapalle', 8);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Chagallu', 8);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Biccavolu', 8);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Anaparthi', 8);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Velairpadu', 11);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Unguturu', 11);
INSERT INTO mandals (mandal_name, district_id) VALUES ('T. Narasapuram', 11);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Polavaram', 11);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Pedavegi', 11);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Pedapadu', 11);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Nuzvid', 11);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Nidamarru', 11);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Musunuru', 11);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Mudinepalle', 11);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Mandavalli', 11);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Lingapalem', 11);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kukunoor', 11);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Koyyalagudem', 11);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kamavarapukota', 11);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kalidindi', 11);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kaikalur', 11);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Jeelugu Milli', 11);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Jangareddygudem', 11);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Eluru', 11);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Dwaraka Tirumala', 11);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Denduluru', 11);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Chintalapudi', 11);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Chatrai', 11);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Buttayagudem', 11);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Bhimadole', 11);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Agiripalli', 11);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Vatticherukuru', 15);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Thullur', 15);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Tenali', 15);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Tadikonda', 15);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Tadepalle', 15);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Prathipadu', 15);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Ponnur', 15);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Phirangipuram', 15);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Pedanandipadu', 15);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Pedakakani', 15);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Medikonduru', 15);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Mangalagiri', 15);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kollipara', 15);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kakumanu', 15);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Guntur West', 15);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Guntur East', 15);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Duggirala', 15);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Chebrolu', 15);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Yeleswaram', 7);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Tuni', 7);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Thondangi', 7);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Thallarevu', 7);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Sankhavaram', 7);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Samalkota', 7);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Rowthulapudi', 7);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Prathipadu', 7);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Pithapuram', 7);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Peddapuram', 7);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Pedapudi', 7);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kothapalle', 7);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kotananduru', 7);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kirlampudi', 7);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Karapa', 7);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kakinada Urban', 7);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kakinada Rural', 7);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kajuluru', 7);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Jaggampeta', 7);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Gollaprolu', 7);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Gandepalle', 7);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Vuyyuru', 13);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Unguturu', 13);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Thotlavalluru', 13);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Penamaluru', 13);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Pedaparupudi', 13);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Pedana', 13);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Pamidimukkala', 13);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Pamarru', 13);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Nandivada', 13);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Nagayalanka', 13);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Movva', 13);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Mopidevi', 13);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Machilipatnam', 13);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kruthivennu', 13);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Koduru', 13);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kankipadu', 13);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Guduru', 13);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Gudlavalleru', 13);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Gudivada', 13);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Ghantasala', 13);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Gannavaram', 13);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Challapalli', 13);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Bapulapadu', 13);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Bantumilli', 13);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Avanigadda', 13);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Yemmiganur', 25);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Veldurthi', 25);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Tuggali', 25);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Pedda Kadubur', 25);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Pattikonda', 25);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Orvakal', 25);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Nandavaram', 25);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Mantralayam', 25);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Maddikera East', 25);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kurnool Urban', 25);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kurnool Rural', 25);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Krishnagiri', 25);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kowthalam', 25);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kosigi', 25);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kodumur', 25);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kallur', 25);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Holagunda', 25);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Halaharvi', 25);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Gudur', 25);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Gonegandla', 25);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Devanakonda', 25);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Chippagiri', 25);
INSERT INTO mandals (mandal_name, district_id) VALUES ('C.Belagal', 25);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Aspari', 25);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Alur', 25);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Adoni', 25);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Velgodu', 26);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Uyyalawada', 26);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Srisailam', 26);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Sirivella', 26);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Sanjamala', 26);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Rudravaram', 26);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Peapally', 26);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Panyam', 26);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Pamulapadu', 26);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Pagidyala', 26);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Owk', 26);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Nandyal Urban', 26);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Nandyal Rural', 26);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Nandikotkur', 26);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Midthuru', 26);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Mahanandi', 26);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kothapalle', 26);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kolimigundla', 26);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Koilkuntla', 26);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Jupadu Bungalow', 26);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Gospadu', 26);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Gadivemula', 26);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Dornipadu', 26);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Dhone', 26);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Chagalamarri', 26);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Bethamcherla', 26);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Bandi Atmakur', 26);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Banaganapalle', 26);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Atmakur', 26);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Allagadda', 26);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Vissannapeta', 12);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Vijayawada West', 12);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Vijayawada Rural', 12);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Vijayawada North', 12);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Vijayawada East', 12);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Vijayawada Central', 12);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Veerullapadu', 12);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Vatsavai', 12);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Tiruvuru', 12);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Reddigudem', 12);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Penuganchiprolu', 12);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Nandigama', 12);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Mylavaram', 12);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kanchikacherla', 12);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Jaggayyapeta', 12);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Ibrahimpatnam', 12);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Gampalagudem', 12);
INSERT INTO mandals (mandal_name, district_id) VALUES ('G.Konduru', 12);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Chandarlapadu', 12);
INSERT INTO mandals (mandal_name, district_id) VALUES ('A. Konduru', 12);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Vinukonda', 14);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Veldurthi', 14);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Savalyapuram', 14);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Sattenapalle', 14);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Rompicherla', 14);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Rentachintala', 14);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Rajupalem', 14);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Piduguralla', 14);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Pedakurapadu', 14);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Nuzendla', 14);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Nekarikallu', 14);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Narasaraopet', 14);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Nadendla', 14);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Muppalla', 14);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Macherla', 14);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Machavaram', 14);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Krosuru', 14);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Karempudi', 14);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Ipuru', 14);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Gurazala', 14);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Edlapadu', 14);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Durgi', 14);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Dachepalle', 14);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Chilakaluripet', 14);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Bollapalle', 14);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Bellamkonda', 14);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Atchampet', 14);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Amaravathi', 14);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Veeraghattam', 2);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Seethanagaram', 2);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Seethampeta', 2);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Salur', 2);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Parvathipuram', 2);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Palakonda', 2);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Pachipenta', 2);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Makkuva', 2);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kurupam', 2);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Komarada', 2);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Jiyyammavalasa', 2);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Gummalakshmipuram', 2);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Garugubilli', 2);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Bhamini', 2);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Balijipeta', 2);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Zarugumilli', 17);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Yerragondapalem', 17);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Veligandla', 17);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Tripuranthakam', 17);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Thallur', 17);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Tarlupadu', 17);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Tangutur', 17);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Singarayakonda', 17);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Santhanuthala Padu', 17);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Racherla', 17);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Pullalacheruvu', 17);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Ponnaluru', 17);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Podili', 17);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Pedacherlo Palle', 17);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Peda Araveedu', 17);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Pamuru', 17);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Ongole', 17);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Naguluppalapadu', 17);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Mundlamuru', 17);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Marripudi', 17);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Markapuram', 17);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Maddipadu', 17);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kurichedu', 17);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kotha Patnam', 17);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kondapi', 17);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Konakanamitla', 17);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Komarolu', 17);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kanigiri', 17);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Hanumanthuni Padu', 17);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Giddalur', 17);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Dornala', 17);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Donakonda', 17);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Darsi', 17);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Cumbum', 17);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Chimakurthi', 17);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Chandra Sekhara Puram', 17);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Bestawaripeta', 17);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Ardhaveedu', 17);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Voletivaripalem', 18);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Vinjamuru', 18);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Vidavaluru', 18);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Venkatachalam', 18);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Varikuntapadu', 18);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Ulavapadu', 18);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Udayagiri', 18);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Thotapalligudur', 18);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Sitarampuramu', 18);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Sangam', 18);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Saidapuramu', 18);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Rapuru', 18);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Podalakuru', 18);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Nellore Urban', 18);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Nellore Rural', 18);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Muttukuru', 18);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Marripadu', 18);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Manubolu', 18);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Lingasamudram', 18);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kovur', 18);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kondapuram', 18);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kodavaluru', 18);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kavali', 18);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kandukur', 18);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kaluvoya', 18);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kaligiri', 18);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Jaladanki', 18);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Indukurpet', 18);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Gudluru', 18);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Duttaluru', 18);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Dagadarthi', 18);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Chejerla', 18);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Buchireddypalem', 18);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Bogolu', 18);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Atmakur', 18);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Anumasamudrampeta', 18);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Ananthasagaram', 18);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Allur', 18);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Tanakal', 24);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Talupula', 24);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Tadimarri', 24);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Somandepalle', 24);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Rolla', 24);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Roddam', 24);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Ramagiri', 24);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Puttaparthi', 24);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Penukonda', 24);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Parigi', 24);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Obuladevaracheruvu', 24);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Nambulapulakunta', 24);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Nallamada', 24);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Nallacheruvu', 24);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Mudigubba', 24);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Madakasira', 24);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Lepakshi', 24);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kothacheruvu', 24);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kanaganapalle', 24);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kadiri', 24);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Hindupur', 24);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Gudibanda', 24);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Gorantla', 24);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Gandlapenta', 24);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Dharmavaram', 24);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Chilamathur', 24);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Chennekothapalle', 24);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Bukkapatnam', 24);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Bathalapalle', 24);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Amarapuram', 24);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Amadagur', 24);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Agali', 24);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Vajrapukothuru', 1);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Tekkali', 1);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Srikakulam', 1);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Sompeta', 1);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Sarubujjili', 1);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Saravakota', 1);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Santhabommali', 1);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Ranastalam', 1);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Ponduru', 1);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Polaki', 1);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Pathapatnam', 1);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Palasa', 1);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Narasannapeta', 1);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Nandigam', 1);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Meliaputti', 1);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Mandasa', 1);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Laveru', 1);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Lakshminarsupeta', 1);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kothuru', 1);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kotabommali', 1);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kaviti', 1);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kanchili', 1);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Jalumuru', 1);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Ichchapuram', 1);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Hiramandalam', 1);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Gara', 1);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Ganguvarisigadam', 1);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Etcherla', 1);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Burja', 1);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Amadalavalasa', 1);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Yerravaripalem', 19);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Yerpedu', 19);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Venkatagiri', 19);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Varadaiahpalem', 19);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Vakadu', 19);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Vadamalapeta', 19);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Tirupati Urban', 19);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Tirupati Rural', 19);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Thottambedu', 19);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Tada', 19);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Sullurpeta', 19);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Srikalahasti', 19);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Satyavedu', 19);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Renigunta', 19);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Ramachandrapuram', 19);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Puttur', 19);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Pichatur', 19);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Pellakuru', 19);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Pakala', 19);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Ojili', 19);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Narayanavanam', 19);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Naidupeta', 19);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Nagalapuram', 19);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kota', 19);
INSERT INTO mandals (mandal_name, district_id) VALUES ('K. V. B. Puram', 19);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Gudur', 19);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Doravarisatram', 19);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Dakkili', 19);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Chittamur', 19);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Chinnagottigallu', 19);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Chillakur', 19);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Chandragiri', 19);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Buchinaidu Kandriga', 19);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Balayapalli', 19);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Visakhapatnam Rural', 4);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Seethammadhara', 4);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Pendurthi', 4);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Pedagantyada', 4);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Padmanabham', 4);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Mulagada', 4);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Maharanipeta', 4);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Gopalapatnam', 4);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Gajuwaka', 4);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Bheemunipatnam', 4);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Anandapuram', 4);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Vizianagaram', 3);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Vepada', 3);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Vangara', 3);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Therlam', 3);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Srungavarapukota', 3);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Santhakaviti', 3);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Regidi Amadalavalasa', 3);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Ramabhadrapuram', 3);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Rajam', 3);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Pusapatirega', 3);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Nellimarla', 3);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Merakamudidam', 3);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Mentada', 3);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Lakkavarapukota', 3);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kothavalasa', 3);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Jami', 3);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Gurla', 3);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Garividi', 3);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Gantyada', 3);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Gajapathinagaram', 3);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Denkada', 3);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Dattirajeru', 3);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Cheepurupalle', 3);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Bondapalle', 3);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Bobbili', 3);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Bhogapuram', 3);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Badangi', 3);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Yelamanchili', 10);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Veeravasaram', 10);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Undi', 10);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Tanuku', 10);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Tadepalligudem', 10);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Poduru', 10);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Penumantra', 10);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Penugonda', 10);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Pentapadu', 10);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Palakollu', 10);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Palacoderu', 10);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Mogalthur', 10);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kalla', 10);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Iragavaram', 10);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Ganapavaram', 10);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Bhimavaram', 10);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Attili', 10);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Akividu', 10);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Achanta', 10);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Yerraguntla', 22);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Vontimitta', 22);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Vemula', 22);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Vempalle', 22);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Veerapunayunipalle', 22);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Vallur', 22);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Thondur', 22);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Sri Avadhutha Kasinayana', 22);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Simhadripuram', 22);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Sidhout', 22);
INSERT INTO mandals (mandal_name, district_id) VALUES ('S.Mydukur', 22);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Rajupalem', 22);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Pulivendla', 22);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Proddatur', 22);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Porumamilla', 22);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Pendlimarri', 22);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Peddamudium', 22);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Mylavaram', 22);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Muddanur', 22);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Lingala', 22);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kondapuram', 22);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Khajipet', 22);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kamalapuram', 22);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kalasapadu', 22);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Kadapa', 22);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Jammalamadugu', 22);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Gopavaram', 22);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Duvvur', 22);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Chinthakommadinne', 22);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Chennur', 22);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Chapad', 22);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Chakrayapet', 22);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Brahmamgarimattam', 22);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Badvel', 22);
INSERT INTO mandals (mandal_name, district_id) VALUES ('B. Kodur', 22);
INSERT INTO mandals (mandal_name, district_id) VALUES ('Atlur', 22);

-- =====================================================
-- VERIFICATION QUERIES
-- =====================================================

-- Count mandals per district
SELECT 
    d.district_name,
    COUNT(m.mandal_id) as mandal_count
FROM districts d
LEFT JOIN mandals m ON d.district_id = m.district_id
WHERE d.state_id = 1
GROUP BY d.district_id, d.district_name
ORDER BY d.district_name;

-- Total mandals
SELECT COUNT(*) as total_mandals FROM mandals 
WHERE district_id IN (SELECT district_id FROM districts WHERE state_id = 1);

-- Success message
SELECT 
    '✅ Successfully loaded ' || COUNT(*) || ' mandals across 26 districts!' as status
FROM mandals 
WHERE district_id IN (SELECT district_id FROM districts WHERE state_id = 1);
